services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/jira
      - SPRING_DATASOURCE_USERNAME=jira
      - SPRING_DATASOURCE_PASSWORD=JiraRush
      - PROD_HOST_PORT=8080
    depends_on:
      db:
        condition: service_healthy
      nginx:
        condition: service_started
    networks:
      - app_network
  db:
    image: postgres:latest
    healthcheck: # ← Вот это блок!
      test: [ "CMD-SHELL", "pg_isready -U jira" ]  # Проверяет доступность БД
      interval: 5s  # Проверка каждые 5 секунд
      timeout: 5s   # Таймаут проверки
      retries: 10   # Количество попыток
    environment:
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: JiraRush
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_for_project
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/nginx.conf
networks:
  app_network:
    driver: bridge

