spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/jira}
    username: ${DB_USERNAME:jira}
    password: ${DB_PASSWORD:JiraRush}

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${OAUTH_GITHUB_CLIENT_ID}
            client-secret: ${OAUTH_GITHUB_CLIENT_SECRET}
            scope:
              - email
          google:
            client-id: ${OAUTH_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          gitlab:
            client-id: ${OAUTH_GITLAB_CLIENT_ID}
            client-secret: ${OAUTH_GITLAB_CLIENT_SECRET}
            client-name: GitLab
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: read_user
        provider:
          gitlab:
            authorization-uri: https://gitlab.com/oauth/authorize
            token-uri: https://gitlab.com/oauth/token
            user-info-uri: https://gitlab.com/api/v4/user
            user-name-attribute: email
  # Mail settings
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: ${MAIL_SMTP_STARTTLS}
          auth: ${MAIL_SMTP_AUTH}
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT}